# Generated by Django 5.0.1 on 2024-02-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twamitraApp', '0018_professions_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='alias',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
