# Generated by Django 5.0.1 on 2024-02-18 22:14

import django.db.models.deletion
import twamitraApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twamitraApp', '0019_servicetype_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatedb',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=twamitraApp.models.corporate_profile_pic_path),
        ),
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('pan', models.CharField(max_length=20, null=True)),
                ('profilePic', models.ImageField(null=True, upload_to=twamitraApp.models.user_profile_pic_path)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
