# Generated by Django 5.0.1 on 2024-02-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twamitraApp', '0020_alter_corporatedb_profilepic_userdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateappointment',
            name='corporate_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corporateappointment',
            name='customer_complete',
            field=models.BooleanField(default=False),
        ),
    ]
