# Generated by Django 5.0.1 on 2024-02-22 20:28

import twamitraApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twamitraApp', '0021_corporateappointment_corporate_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatedb',
            name='profilePic',
            field=models.ImageField(default='userDefault.svg', null=True, upload_to=twamitraApp.models.corporate_profile_pic_path),
        ),
    ]
