# Generated by Django 5.0.1 on 2024-02-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twamitraApp', '0023_corporatedb_rating_loandetail_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatedb',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
